### ISSUE TITLE
Adding this to themes.getnikola.com

### ISSUE THREAD

**Issue by ralsina** [magmax/nikola-theme-octopress#1]
Hi!

Would you mind if I did some git trickery to get this to appear in themes.getnikola.com ?

Thanks in advance if you approve :-)

**Comment by magmax** [comment]
Hi!

I did a lot of tricks in order to get it as I wanted to. Some of them are not "standard" and it requires some different configuration.

In addition, it is not completely documented.

But... well, this is free software and any way to increase its visibility is welcome ;)
