### ISSUE TITLE
This theme is broken.

### ISSUE THREAD

**Issue by Kwpolska** [magmax/nikola-theme-octopress#5]
This theme lacks support for:
- basic Nikola building blocks, such as `extra_head`
- Nikola default comments
- new list.tmpl (#4)

It also has a weird file structure that hinders modifications.

If there is no response by Saturday **2016-03-05**, the theme will be deleted from the Index due to not following Nikola theming standards.

**Comment by ralsina** [comment]
I wll try to get a PR before that date :-)

**Comment by Kwpolska** [comment]
Another issue: https://github.com/getnikola/nikola-themes/issues/73

**Comment by Kwpolska** [comment]
The deadline has passed and the theme has been removed.

**Comment by magmax** [comment]
Yes: this theme doesn't fit Nikola standards and it is good it to be removed.
